FROM node:22.18.0-slim

RUN apt-get update && apt install -y \
  curl && \
  npm install -g nodemon

COPY start.sh /
RUN chmod +x /start.sh

# debian
# RUN useradd -m -u 1000 xpto

# alpine
# RUN adduser -D -u 1000 xpto

USER node

WORKDIR /home/node/app

# COPY --chown=node:node package*.json ./
# RUN npm install

EXPOSE 3000

# CMD ["tail", "-f", "/dev/null"]
# CMD ["sh", "-c", "npm install && tail -f /dev/null"]

CMD [ "/start.sh" ]
