# Seria o `docker-compose.dev.yml` mais para fins didaticos criamos esse
include:
  - ./external-api/docker-compose.external-api.yaml
services:
  web1:
    extends:
      file: ./docker-compose.common.yaml
      service: web
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
        #restart: true
  web2:
    extends:
      file: ./docker-compose.common.yaml
      service: web
    profiles: [nginx]
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
        #restart: true

  nginx:
    build: ./.docker/nginx
    profiles: [nginx]
    restart: always
    ports:
      - "4000:80"
    develop:
      watch:
        - action: sync+restart
          x-initialSync: true
          path: ./.docker/nginx/nginx.conf
          target: /etc/nginx/nginx.conf

  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s # Frequencia em que o Healthcheck é executado
      timeout: 5s # Tempo limite para o Healthcheck
      retries: 5 # Tentativas antes de considerar o container como unhealthy
      start_period: 10s # Tempo de espera antes de iniciar o Healthcheck
#     networks:
#       - external-api_default

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    profiles: [debug]
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - db

# networks:
#   external-api_default:
#     external: true